import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProviders } from "../providers/ThemeProviders";
import { QueryProvider } from "@/providers/QueryProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviders>
          <QueryProvider>{children}</QueryProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
